const mongoose = require("mongoose");

const recoverySchema = new mongoose.Schema(
  {
    paymentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Payment",
      required: true,
    },

    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Customer",
    },
    paymentLinkId: {
     type: String,
    },

    // AI confidence that payment can be recovered
    recoveryProbability: {
      type: Number,
      min: 0,
      max: 1,
    },

    // AI risk assessment
    riskLevel: {
      type: String,
      enum: ["low", "medium", "high"],
    },

    // AI urgency
    urgency: {
      type: String,
      enum: ["low", "medium", "high"],
    },

    // AI selected action
    aiDecision: {
      type: String,
      enum: [
        "retry",
        "payment_link",
        "discount",
        "human_escalation",
        "do_nothing",
      ],
    },

    recommendedAction: String,

    // Explanation generated by AI
    aiReason: String,

    // Message that can be sent to customer
    customerMessage: String,

    // Recovery workflow status
    status: {
      type: String,
      enum: [
        "pending",
        "executed",
        "recovered",
        "failed",
        "stopped",
      ],
      default: "pending",
    },

    // Number of recovery attempts
    attempts: {
      type: Number,
      default: 0,
    },

    stoppedReason: String,
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model(
  "Recovery",
  recoverySchema
);